// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0lIFGHOQuXJ6nnF0IC4NHa_qxH0r_6h0',
    appId: '1:156364345285:web:bc65216101f5331d5605ac',
    messagingSenderId: '156364345285',
    projectId: 'movilesfinal-98b01',
    authDomain: 'movilesfinal-98b01.firebaseapp.com',
    storageBucket: 'movilesfinal-98b01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6VwkmHQDRcbwUwvwOl1Xlz1n5KKa2S5g',
    appId: '1:156364345285:android:01cf9075fef4a4955605ac',
    messagingSenderId: '156364345285',
    projectId: 'movilesfinal-98b01',
    storageBucket: 'movilesfinal-98b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvTC9EK6fR0veuq3Td0keP_ebM_pb3Wc',
    appId: '1:156364345285:ios:da23b8c27322900b5605ac',
    messagingSenderId: '156364345285',
    projectId: 'movilesfinal-98b01',
    storageBucket: 'movilesfinal-98b01.appspot.com',
    iosClientId: '156364345285-sq3lg3tpqfn2s47qhn522483tmn8n5v2.apps.googleusercontent.com',
    iosBundleId: 'm.p.finalmoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvvTC9EK6fR0veuq3Td0keP_ebM_pb3Wc',
    appId: '1:156364345285:ios:da23b8c27322900b5605ac',
    messagingSenderId: '156364345285',
    projectId: 'movilesfinal-98b01',
    storageBucket: 'movilesfinal-98b01.appspot.com',
    iosClientId: '156364345285-sq3lg3tpqfn2s47qhn522483tmn8n5v2.apps.googleusercontent.com',
    iosBundleId: 'm.p.finalmoviles',
  );
}
